version:  '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=jesus
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
